# Generated by Django 3.1.7 on 2021-05-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracecap_ui', '0002_auto_20210503_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracecapture',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracecap_ui.project'),
        ),
    ]
